### ISSUE TITLE
add variable correlation matrix / plot

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilReports#10]
Ideas:
- https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html

**Comment by pierreroudier** [comment]
Also see visualisation ideas using [the`ggcorr` package](https://briatte.github.io/ggcorr/).

**Comment by dylanbeaudette** [comment]
`Hmisc::varclust`

**Comment by dylanbeaudette** [comment]
Well, `Hmisc` is already installed via dependencies so `Hmisc::varclus` should be fine. Added with 7554f8e126312430717223869a6b42fd6ba39a0e
