### ISSUE TITLE
Modernizing .Rprofile

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilReports#115]
The .Rprofile created by `installRprofile()` handles a few possible issues with CCE machines, but it may be time to re-evaluate the assumptions. It remaps the HOME directory to a local drive, and sets the user R library path also to a local drive. 

Possibly some of the core assumptions need to be re-evaluated given the recent "OneDrive migration".

In last Stats for Soil Survey class we have had some issues with installing R profile on machines where usernames do not match up with user directory, and also folks who already had home on OneDrive. Therefore it is now possible to customize both the target local drive and the user name in the call to `installRprofile()`. 

We want to be sure that standard NCSS .Rprofile will work for as many users as possible out of the box via:
```r
source('https://raw.githubusercontent.com/ncss-tech/soilReports/master/R/installRprofile.R')
installRprofile(overwrite=TRUE)
```

### Issue Item 1:
We set the HOME environment variable to:
```sh
'C:/Users/<USERNAME>/Documents/'
```

And then force the user R library into a subdirectory of this new HOME:
```sh
'C:/Users/<USERNAME>/Documents/R/win-library/4.2'
```

This works to get the packages off of a network drive, but following path is probably a more appropriate/generic choice on Windows:
```sh
'C:/Users/<USERNAME>/AppData/Local/R/win-library/4.2'
```

### Issue Item 2:
It seems that setting system environment variable `HOME` may not be sufficient to ensure that `path.expand("~")` will return a customized value. I am not sure what has caused this (as I believe this was not the case in January when I made the most recent revisions to the standard .Rprofile), so creating an issue to track it

**Comment by brownag** [comment]
Related : https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What-are-HOME-and-working-directories_003f

**Comment by brownag** [comment]
A note that manually setting HOME user environment variable works to change the default home directory, but `Sys.setenv(HOME="...")` does _not_ seem to work anymore (nor any of the other vars e.g. R_USER).

**Comment by brownag** [comment]
This seems to still be an issue after completing my OneDrive migration.

**Comment by brownag** [comment]
Since R 4.2 release the default personal library location is `$LOCALAPPDATA`. 

So, we can omit any changes to the `.libPaths()` in our new .Rprofile.

It is less of a problem that `~` expands to OneDrive Documents folder... just possibly unexpected based on how it used to work, and what our .Rprofile was doing on 4.1.x. Using OneDrive as `~` this might be "good" in terms making it easy to automatically have "archiving" of scripts, and being able to use them on different computers easily; but if folks want to work around this they can set `$HOME` manually. I generally prefer having "~" expand to a local drive for the sake of speed/not having a chance of syncing affect read/write or intermediate files I do not need archived. I can't prove that this causes any significant overhead, just a suspicion.

For my purposes I prefer to just use my User folder (`C:\Users\Andrew.G.Brown\`) as HOME.

![image](https://user-images.githubusercontent.com/20842828/184696156-738d633a-467a-468e-930b-509b47bfdba3.png)


From https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What_0027s-the-best-way-to-upgrade_003f
> For those with a personal library (folder R\win-library\x.y of your ${LOCALAPPDATA} directory in R since 4.2.0, or of your home directory with earlier versions of R), you will need to update that too when the minor version of R changes (e.g. from 4.0.2 to 4.1.0). A simple way to do so is to copy (say) R\win-library\4.0 to R\win-library\4.1 before running update.packages(checkBuilt=TRUE, ask=FALSE).

My thinking now is to remove references to creating an .Rprofile from the pre-course assignment. As far as I can tell at this point it is not necessary anymore, and changing lib paths may even create problems (i.e. a remote package lib) depending on if HOME is defined. 

We can replace .Rprofile with an optional redirect of `$HOME` implemented via user environment variables dialog if we think that is necessary, but I would argue it probably isn't--as having the `C:/workspace2` scratch working directory as a fallback when not in a project covers most usage.

**Comment by brownag** [comment]
Would anyone have objections to me removing the .Rprofile bits from the stats for soil survey precourse assignment / CCE R setup?

**Comment by hammerly** [comment]
I don't have an objection to this.

**Comment by dylanbeaudette** [comment]
Go for it.

**Comment by brownag** [comment]
Done
