### ISSUE TITLE
Extending reportInit/reportSetup to handle a "report manifest" 

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilReports#45]
Currently, we assume that every report is comprised of report.Rmd, config.R and setup.R files, but sometimes these are not the only documents that would need to be copied by reportInit(). 

Examples of this case are: 
1. region11 lab summary reports (using custom.R)
2. Shiny interactive pedon summary report (currently under region2 in branch 'AGB')

A few questions for your consideration:
- Should setup.R be extended to include a variable (e.g. files_to_copy; vector of directories and files to copy) that lists additional items to be copied when creating a new report instance? 
- Should we distinguish reports that have an interactive/dashboard component (i.e. 'has_dashboard' boolean that indicates presence of shiny.Rmd or equivalent)?
- Should the report metadata (currently stored at top of report.Rmd) be moved to a set of metadata variables in setup.R?

**Comment by dylanbeaudette** [comment]
Yes to all questions. It would be nice to have all report-related setup and documentation in a single place. The code used to extract the metadata from `report.Rmd` is a hack, much simpler to get it from `setup.R`.

Feel free to implement as time permits.

**Comment by dylanbeaudette** [comment]
I am suggesting the following changes:

1. move file manifest (currently a mixture of `initReport()` and `custom.R`) into a character vector, stored in `setup.R`.

2. set all report-related metadata in `setup.R` and remove from the top chunk of `report.Rmd`

**Comment by brownag** [comment]
That sounds good to me. Probably would be overkill to create a separate manifest file... especially if files will be specified using R code rather than in just a flat file. setup.R is typically pretty sparse so that will fill it in nicely. 

Also, will be good to get that metadata over into the setup for easier access outside the Rmd.

I think I still like the idea of programmatically concatenating a brief description (report nam & version) as an HTML comment right before the YAML header when creating a new report instance via reportInit().

So, you would have something like:

```
<!-- region2/mu-comparison (version 2.5) - instance created 06/21/2017 15:30 PST -->
---
title: Mapunit Comparison Report
output:
  html_document:
    mathjax: null
    jquery: null
    smart: no
    keep_md: no
---
```

**Comment by brownag** [comment]
Will be ready to fast-forward master branch with this update once all reports have had their setup.R files updated. 

As of 8cfe7b6e764bb6e0e74855ed0fbcc14782888495 on branch ReportManifest, only region2/mu-comparison makes use of the new format.
