### ISSUE TITLE
abbreviateNames() does not always return unique names

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilReports#47]
This is typically only a problem when someone has created their input features (`mu`) with many tables joined to it. Some options:

 * filter out all columns except `mu.col`
 * smarter `abbreviateNames()`

The context of this error is:

```r
poly.check.wide <- dcast(polygons.to.check, pID ~ variable, value.var = 'prop.outside.range')
poly.check.wide[is.na(poly.check.wide)] = 0 #replace NAs with zero (no samples outside 5-95% percentile range)

mu.check <- merge(mu, poly.check.wide, by='pID', all.x=TRUE)
names(mu.check)[-1] <- abbreviateNames(mu.check)

# fix names for printing
names(polygons.to.check)[1] <- mu.col

# print table (removed from report now that shapefile with proportions outside range is generated)
#kable(polygons.to.check[display.idx,], row.names = FALSE) #only shows polys with p.crit > 0.15 in report tabular output

#save a SHP file with prop.outside.range for each polygon and raster data source combination
if(nrow(polygons.to.check) > 0) {
  shp.fname <- paste0('poly-qc-', paste(mu.set, collapse='_'))
  writeOGR(mu.check, dsn='output', layer=shp.fname, driver='ESRI Shapefile', overwrite_layer=TRUE)
  write.csv(mu.check,file=paste0("output\\",shp.fname,".csv")) 
}
```

**Comment by brownag** [comment]
With #53, there is the potential for a large number of additional "spatial proportion summary"-type output coming through in these SHP files. These could turn out to be ambiguous when truncated by abbreviateNames() as well. Where in the past this output was limited to geomorphons, it is currently generated for any categorical dataset where `do.spatial.summary == FALSE` in the definitions file for that layer.

Also, somewhat unrelated, abbreviateNames() might be a good function addition to `sharpshootR`. Dealing with the limitations of DBF files and coming up with sensible abbreviations crops up all the time, not just in the context of generating report output.

**Comment by dylanbeaudette** [comment]
I have seen this happen when using the EPA eco-regions as the polygon input.

**Comment by dylanbeaudette** [comment]
A very simple fix:

```r
# in order to avoid column name collisions due to DBF limitations, keep only the mu.col column
mu <- mu[, mu.col, drop=FALSE]
```

Sometimes you have to throw the baby out with the bath water.
