### ISSUE TITLE
test for invalid musym in mu.set

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilReports#65]
Problems occur when/if an invalid (e.g. missing, typo, correlated-to-something-else) musym is specified in the `mu.set` variable, from config.R. This isn't common, but could happen during progressive mapping or when a map unit has been "correlated away".

Solution: new function to remove invalid symbols and set factor levels accordingly.

Related: factor levels should be preserved in a more consistent manner.

**Comment by brownag** [comment]
c21945c8c767976d97dd2e914e9604245ad55250
